#docker-compose -f docker-compose-app.yml up -d

version: '3.8'

services:
  auth-service:
    build:
      context: ./com.msa_delivery.auth # auth-service 디렉토리 경로
      dockerfile: Dockerfile
    ports:
      - "19094:19094" # Expose와 일치
    networks:
      - my-network
#    depends_on:
#      eureka-service:
#        condition: service_healthy
#      gateway-service:
#        condition: service_healthy

  user-service:
    build:
      context: ./com.msa_delivery.user # user-service 디렉토리 경로
      dockerfile: Dockerfile
    ports:
      - "19095:19095" # Expose와 일치
    networks:
      - my-network
#    depends_on:
#      eureka-service:
#        condition: service_healthy
#      gateway-service:
#        condition: service_healthy

networks:
  my-network:
    driver: bridge