server:
  port: ${ORDER_PORT}

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${ORDER_SCHEMA}
        dialect: ${JPA_DIALECT}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

googleai:
  api:
    key: ${GOOGLE_API_KEY}
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    components:
      circuitbreaker:
        enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 3000
      database: 0
