
server:
  port: ${AUTH_PORT}

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${AUTH_SCHEMA}
        dialect: ${JPA_DIALECT}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s
  retry:
    instances:
      defaultRetry:
        maxAttempts: 3
        waitDuration: 1000ms

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    components:
      circuitbreaker:
        enabled: true

service:
  jwt:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    secret-key: ${JWT_SECRET_KEY}