
server:
  port: ${HUB_PORT}

spring:
  application:
    name: hub-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${HUB_SCHEMA}
        dialect: ${JPA_DIALECT}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL}
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "hub::"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

kakao:
  api:
    key: ${KAKAO_API_KEY}
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    components:
      circuitbreaker:
        enabled: true
